### ISSUE TITLE
Problem w/Python binding

### ISSUE THREAD

**Issue by pmagwene** [monome/libmonome#22]
I'm trying to use the Python bindings. Latest version w/waf build on OS X 10.7, Python 2.7.1

```
>>> from monome import Monome
>>> m = Monome("osc.udp://127.0.0.1:9000/monome", "8000")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "monome.pyx", line 260, in monome.Monome.__init__ (monome.c:2342)
    self.devpath = (monome_get_devpath(self.monome)).decode()
TypeError: Expected str, got unicode
```

**Comment by coreyker** [comment]
I'm new to using libmonome, but I just tried to run the example `examples/test_arc.py` and I get this same error:
```
Traceback (most recent call last):
  File "examples/test_arc.py", line 55, in <module>
    main()
  File "examples/test_arc.py", line 46, in main
    m = monome.Monome('/dev/tty.usbserial-m0000002')
  File "monome.pyx", line 319, in monome.Monome.__init__
TypeError: Expected unicode, got str
```
